on:
  workflow_dispatch: null
jobs:
  build:
    name: Run script
    runs-on: ubuntu-latest
    env:
      TWINS_USERNAME: ${{ secrets.TWINS_USERNAME }}
      TWINS_PASSWORD: ${{ secrets.TWINS_PASSWORD }}
      GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ubuntu-latest-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ubuntu-latest-
      - uses: actions/setup-node@v2
        with:
          node-version: "15"
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3
          run_install: true
      - name: Build
        run: pnpm main
        env:
          DEBUG: octokit:rest*
